/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';




export namespace Components {

  interface MobyButton {
    'classes': string;
    'loader': boolean;
    /**
    * Props
    */
    'title': string;
  }
  interface MobyButtonAttributes extends StencilHTMLAttributes {
    'classes'?: string;
    'loader'?: boolean;
    /**
    * Props
    */
    'title'?: string;
  }
}

declare global {
  interface StencilElementInterfaces {
    'MobyButton': Components.MobyButton;
  }

  interface StencilIntrinsicElements {
    'moby-button': Components.MobyButtonAttributes;
  }


  interface HTMLMobyButtonElement extends Components.MobyButton, HTMLStencilElement {}
  var HTMLMobyButtonElement: {
    prototype: HTMLMobyButtonElement;
    new (): HTMLMobyButtonElement;
  };

  interface HTMLElementTagNameMap {
    'moby-button': HTMLMobyButtonElement
  }

  interface ElementTagNameMap {
    'moby-button': HTMLMobyButtonElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
